Layout/DotPosition:
  EnforcedStyle: trailing

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/AccessorGrouping:
  EnforcedStyle: separated
