

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardlessPro
  # A module containing classes for each of the resources in the GC Api
  module Resources
    # Mandate PDFs allow you to easily display [scheme-rules
    # compliant](#ui-compliance-requirements) Direct Debit mandates to your
    # customers.
    # Represents an instance of a mandate_pdf resource returned from the API
    class MandatePdf
      attr_reader :expires_at

      attr_reader :url
      # initialize a resource instance
      # @param object [Hash] an object returned from the API
      def initialize(object, response = nil)
        @object = object

        @expires_at = object['expires_at']
        @url = object['url']
        @response = response
      end

      def api_response
        ApiResponse.new(@response)
      end

      # Provides the resource as a hash of all it's readable attributes
      def to_h
        @object
      end
    end
  end
end
