

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardlessPro
  # A module containing classes for each of the resources in the GC Api
  module Resources
    # Check whether an account number and bank / branch code combination are
    # compatible.
    # Represents an instance of a modulus_check resource returned from the API
    class ModulusCheck
      attr_reader :available_schemes

      attr_reader :errors

      attr_reader :succeeded
      # initialize a resource instance
      # @param object [Hash] an object returned from the API
      def initialize(object, response = nil)
        @object = object

        @available_schemes = object['available_schemes']
        @errors = object['errors']
        @succeeded = object['succeeded']
        @response = response
      end

      def api_response
        ApiResponse.new(@response.api_response)
      end

      # Provides the resource as a hash of all it's readable attributes
      def to_h
        @object
      end
    end
  end
end
