

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardless::Enterprise
  module Resources
  # <a name="api_key_not_active"></a>API keys are designed to be used by any
  # integrations you build. You should generate a key and then use it to make
  # requests to the API and set the webhook URL for that integration. They do
  # not expire, but can be disabled.
    class ApiKey < Base
      def initialize(client)
        @client = client
      end
      
    # Creates a new API key.
      # Example URL: /api_keys
      # @param options: any query parameters, in the form of a hash
      def create(options = {})
        make_request(:post, "/api_keys", options)
      end

    # Returns a
    # [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    # list of your API keys.
      # Example URL: /api_keys
      # @param options: any query parameters, in the form of a hash
      def list(options = {})
        make_request(:get, "/api_keys", options)
      end

    # Retrieves the details of an existing API key.
      # Example URL: /api_keys/:identity
      #
      # @param identity:       # Unique identifier, beginning with "AK" }}
      # @param options: any query parameters, in the form of a hash
      def get(identity, options = {})
        path = sub_url("/api_keys/:identity", { 
          "identity" => identity
        })

        make_request(:get, path, options)
      end

    # Updates an API key. Only the `name` and `webhook_url` fields are
    # supported.
      # Example URL: /api_keys/:identity
      #
      # @param identity:       # Unique identifier, beginning with "AK" }}
      # @param options: any query parameters, in the form of a hash
      def update(identity, options = {})
        path = sub_url("/api_keys/:identity", { 
          "identity" => identity
        })

        make_request(:put, path, options)
      end

    # Disables an API key. Once disabled, the API key will not be usable to
    # authenticate any requests, and its `webhook_url` will not receive any more
    # events.
      # Example URL: /api_keys/:identity/actions/disable
      #
      # @param identity:       # Unique identifier, beginning with "AK" }}
      # @param options: any query parameters, in the form of a hash
      def disable(identity, options = {})
        path = sub_url("/api_keys/:identity/actions/disable", { 
          "identity" => identity
        })

        make_request(:post, path, options)
      end

      def envelope_key
        "api_keys"
      end

      def sub_url(url, param_map)
        param_map.reduce(url) do |new_url, (param, value)|
          new_url.gsub(":#{param}", value)
        end
      end
    end
  end
end
