require_relative './base_service'

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardlessPro
  module Services
    # Service for making requests to the BankDetailsLookup endpoints
    class BankDetailsLookupsService < BaseService
      # Performs a bank details lookup.
      #
      # Bank account details may be supplied
      # using [local details](#appendix-local-bank-details) or an IBAN.
      # Example URL: /bank_details_lookups
      # @param options [Hash] parameters as a hash, under a params key.
      def create(options = {})
        path = '/bank_details_lookups'

        params = options.delete(:params) || {}
        options[:params] = {}
        options[:params][envelope_key] = params
        response = make_request(:post, path, options)

        return if response.body.nil?

        Resources::BankDetailsLookup.new(unenvelope_body(response.body), response)
      end

      # Unenvelope the response of the body using the service's `envelope_key`
      #
      # @param body [Hash]
      def unenvelope_body(body)
        body[envelope_key] || body['data']
      end

      private

      # return the key which API responses will envelope data under
      def envelope_key
        'bank_details_lookups'
      end

      # take a URL with placeholder params and substitute them out for the acutal value
      # @param url [String] the URL with placeholders in
      # @param param_map [Hash] a hash of placeholders and their actual values
      def sub_url(url, param_map)
        param_map.reduce(url) do |new_url, (param, value)|
          new_url.gsub(":#{param}", value)
        end
      end
    end
  end
end
