require_relative './base_service'

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardlessPro
  module Services
    # Service for making requests to the MandatePdf endpoints
    class MandatePdfsService < BaseService
      # Generates a temporary URL for viewing a PDF mandate.
      #
      # Bank account details
      # may be supplied using an IBAN (international bank account number), or [local
      # details](#ui-local-bank-details), or alternatively you can provide the ID of
      # an existing [mandate](#core-endpoints-mandates) to create a PDF of.
      #
      # To
      # generate a mandate in a foreign language, set your `Accept-Language` header to
      # the relevant [ISO
      # 639-1](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#Partial_ISO_639_table)
      # language code. Currently Dutch, English, French, German, Italian, Portuguese
      # and Spanish are supported.
      # Example URL: /mandate_pdfs
      # @param options [Hash] parameters as a hash, under a params key.
      def create(options = {})
        path = '/mandate_pdfs'

        params = options.delete(:params) || {}
        options[:params] = {}
        options[:params][envelope_key] = params
        response = make_request(:post, path, options)

        return if response.body.nil?
        Resources::MandatePdf.new(unenvelope_body(response.body), response)
      end

      # Unenvelope the response of the body using the service's `envelope_key`
      #
      # @param body [Hash]
      def unenvelope_body(body)
        body[envelope_key] || body['data']
      end

      private

      # return the key which API responses will envelope data under
      def envelope_key
        'mandate_pdfs'
      end

      # take a URL with placeholder params and substitute them out for the acutal value
      # @param url [String] the URL with placeholders in
      # @param param_map [Hash] a hash of placeholders and their actual values
      def sub_url(url, param_map)
        param_map.reduce(url) do |new_url, (param, value)|
          new_url.gsub(":#{param}", value)
        end
      end
    end
  end
end
