require_relative './base_service'

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardlessPro
  module Services
    # Service for making requests to the OwnSunRequest endpoints
    class OwnSunRequestsService < BaseService
      # Sends an email to GoCardless team members requesting a SUN for the
      # organisation, unless this is the live environment and the organisation already
      # has its own SUN.
      # Example URL: /own_sun_requests
      # @param options [Hash] parameters as a hash, under a params key.
      def create(options = {})
        path = '/own_sun_requests'

        params = options.delete(:params) || {}
        options[:params] = {}
        options[:params][envelope_key] = params
        response = make_request(:post, path, options)

        return if response.body.nil?
        Resources::OwnSunRequest.new(unenvelope_body(response.body), response)
      end

      # Unenvelope the response of the body using the service's `envelope_key`
      #
      # @param body [Hash]
      def unenvelope_body(body)
        body[envelope_key] || body['data']
      end

      private

      # return the key which API responses will envelope data under
      def envelope_key
        'own_sun_request'
      end

      # take a URL with placeholder params and substitute them out for the acutal value
      # @param url [String] the URL with placeholders in
      # @param param_map [Hash] a hash of placeholders and their actual values
      def sub_url(url, param_map)
        param_map.reduce(url) do |new_url, (param, value)|
          new_url.gsub(":#{param}", value)
        end
      end
    end
  end
end
