# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

require 'json'
require 'zlib'
require 'active_support/inflector'
require 'faraday'
require 'time'
require 'active_support/core_ext/hash/indifferent_access'


require 'uri'

module GoCardless
end

version_file = 'enterprise/version'

if File.file? File.expand_path("#{version_file}.rb", File.dirname(__FILE__))
  require_relative version_file
else
  GoCardless::VERSION = ''
end

require_relative 'enterprise/api_service'
require_relative 'enterprise/list_response'
require_relative 'enterprise/error'
require_relative 'enterprise/error/validation_error'
require_relative 'enterprise/error/gocardless_error'
require_relative 'enterprise/error/invalid_api_usage_error'
require_relative 'enterprise/error/invalid_state_error'
require_relative 'enterprise/paginator'
require_relative 'enterprise/request'
require_relative 'enterprise/response'


require_relative 'enterprise/resources/api_key'
require_relative 'enterprise/services/api_key_service'

require_relative 'enterprise/resources/creditor'
require_relative 'enterprise/services/creditor_service'

require_relative 'enterprise/resources/creditor_bank_account'
require_relative 'enterprise/services/creditor_bank_account_service'

require_relative 'enterprise/resources/customer'
require_relative 'enterprise/services/customer_service'

require_relative 'enterprise/resources/customer_bank_account'
require_relative 'enterprise/services/customer_bank_account_service'

require_relative 'enterprise/resources/event'
require_relative 'enterprise/services/event_service'

require_relative 'enterprise/resources/helper'
require_relative 'enterprise/services/helper_service'

require_relative 'enterprise/resources/mandate'
require_relative 'enterprise/services/mandate_service'

require_relative 'enterprise/resources/payment'
require_relative 'enterprise/services/payment_service'

require_relative 'enterprise/resources/payout'
require_relative 'enterprise/services/payout_service'

require_relative 'enterprise/resources/publishable_api_key'
require_relative 'enterprise/services/publishable_api_key_service'

require_relative 'enterprise/resources/redirect_flow'
require_relative 'enterprise/services/redirect_flow_service'

require_relative 'enterprise/resources/refund'
require_relative 'enterprise/services/refund_service'

require_relative 'enterprise/resources/role'
require_relative 'enterprise/services/role_service'

require_relative 'enterprise/resources/subscription'
require_relative 'enterprise/services/subscription_service'

require_relative 'enterprise/resources/user'
require_relative 'enterprise/services/user_service'


module GoCardless

  class Client
    extend Forwardable
  
    def api_keys
      @api_keys ||= Services::ApiKeyService.new(@api_service)
    end
  
    def creditors
      @creditors ||= Services::CreditorService.new(@api_service)
    end
  
    def creditor_bank_accounts
      @creditor_bank_accounts ||= Services::CreditorBankAccountService.new(@api_service)
    end
  
    def customers
      @customers ||= Services::CustomerService.new(@api_service)
    end
  
    def customer_bank_accounts
      @customer_bank_accounts ||= Services::CustomerBankAccountService.new(@api_service)
    end
  
    def events
      @events ||= Services::EventService.new(@api_service)
    end
  
    def helpers
      @helpers ||= Services::HelperService.new(@api_service)
    end
  
    def mandates
      @mandates ||= Services::MandateService.new(@api_service)
    end
  
    def payments
      @payments ||= Services::PaymentService.new(@api_service)
    end
  
    def payouts
      @payouts ||= Services::PayoutService.new(@api_service)
    end
  
    def publishable_api_keys
      @publishable_api_keys ||= Services::PublishableApiKeyService.new(@api_service)
    end
  
    def redirect_flows
      @redirect_flows ||= Services::RedirectFlowService.new(@api_service)
    end
  
    def refunds
      @refunds ||= Services::RefundService.new(@api_service)
    end
  
    def roles
      @roles ||= Services::RoleService.new(@api_service)
    end
  
    def subscriptions
      @subscriptions ||= Services::SubscriptionService.new(@api_service)
    end
  
    def users
      @users ||= Services::UserService.new(@api_service)
    end
  

    # Get a Client configured to use HTTP Basic authentication.
    #
    # @param api_key [String] The API key to use when connecting.
    # @param
    # @param options [Hash<Symbol,String>] Optionally, custom settings
    #   to use with the client.  Allowed option is `default_headers`.
    # @return [Client] A client configured to use the API with HTTP Basic
    #   authentication.
    def initialize(options)
      environment = options.delete(:environment) || :production
      user = options.delete(:user) || raise("No API key ID given to GoCardless Client")
      password = options.delete(:password) || raise("No API secret given to GoCardless Client")
      options = custom_options(options)
      @api_service = ApiService.new(url_for_environment(environment), user, password, options)
    end

    private

    def url_for_environment(environment)
      if environment === :production
        "https://api.gocardless.com"
      elsif environment === :sandbox
        "https://api-sandbox.gocardless.com"
      else
        raise "Unknown environment key: #{environment}"
      end
    end

    # Get customized options.
    def custom_options(options)
      return default_options if options.nil?

      return default_options.merge(options) unless options[:default_headers]

      opts = default_options.merge(options)
      opts[:default_headers] = default_options[:default_headers].merge(options[:default_headers])

      opts
    end

    # Get the default options.
    def default_options
      {
        default_headers: { 
          'GoCardless-Version' => '2014-11-03',
          'User-Agent' => "#{user_agent}",
          'Content-Type' => 'application/json'
        }
      }
    end

    def user_agent
      @user_agent ||=
        begin
          gem_name = "gocardless-enterprise"
          gem_info = "#{gem_name}"
          gem_info += "/v#{ GoCardless::VERSION}" if defined?(GoCardless::VERSION)
          ruby_engine = defined?(RUBY_ENGINE) ? RUBY_ENGINE : 'ruby'
          ruby_version = RUBY_VERSION
          ruby_version += " p#{RUBY_PATCHLEVEL}" if defined?(RUBY_PATCHLEVEL)
          comment = ["#{ruby_engine} #{ruby_version}"]
          comment << "gocardless-enterprise v#{ GoCardless::VERSION}"
          comment << "faraday v#{Faraday::VERSION}"
          comment << RUBY_PLATFORM if defined?(RUBY_PLATFORM)
          "#{gem_info} (#{comment.join("; ")})"
        end
    end
  end
end
