

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardless
  # A module containing classes for each of the resources in the GC Api
  module Resources
    # <a name="insufficient_permissions"></a>Roles represent a set of permissions
    # that may be granted to a user. The permissions are specified at the
    # resource-type level, and can be `full_access` or `read_only`. If a
    # resource-type is not included that role's users will have no access to
    # resources of that type, and will receive an `insufficient_permissions` error
    # when trying to use those endpoints.
    #
    # A role's `permissions`
    # attribute is used to set/show the permissions for a role and it's key/value
    # pairs are restricted to the below:
    #
    # <dl>
    #
    # <dt><p><code>resource</code></p></dt>
    #   <dd><p>One of:</p>
    #     <ul>

    #  #       <li><code>customers</code></li>
    #
    # <li><code>customer_bank_accounts</code></li>
    #
    # <li><code>mandates</code></li>
    #       <li><code>payments</code></li>
    #
    #      <li><code>payouts</code></li>
    #
    # <li><code>creditors</code></li>
    #
    # <li><code>creditor_bank_accounts</code></li>
    #
    # <li><code>roles</code></li>
    #       <li><code>users</code></li>
    #
    # <li><code>events</code></li>
    #       <li><code>api_keys</code></li>
    #
    #    <li><code>subscriptions</code></li>
    #
    # <li><code>redirect_flows</code></li>
    #     </ul>
    #   </dd>
    # </dl>
    #
    #
    # <dl>
    #   <dt><p><code>access</code></p></dt>
    #   <dd><p>One
    # of:</p>
    #     <ul>
    #       <li><code>full_access</code>: read and write
    # all records of this type</li>
    #       <li><code>read_only</code>: list and
    # show endpoints available, but not create, update, delete, or actions</li>

    # #     </ul>
    #   </dd>
    # </dl>
    #
    # Represents an instance of a role resource returned from the API
    class Role
      attr_reader :created_at

      attr_reader :enabled

      attr_reader :id

      attr_reader :name

      attr_reader :permissions
      # initialize a resource instance
      # @param object [Hash] an object returned from the API
      def initialize(object)
        @object = object

        @created_at = object['created_at']
        @enabled = object['enabled']
        @id = object['id']
        @name = object['name']
        @permissions = object['permissions']
      end

      # Provides the resource as a hash of all it's readable attributes
      def to_h
        @object
      end
    end
  end
end
