version: 2.1

jobs:
  test: &test
    parallelism: 1
    parameters:
      faraday-version: { type: string }
      ruby-version: { type: string }
    docker:
      - image: ruby:<<parameters.ruby-version>>
        environment:
          - FARADAY_VERSION=<<parameters.faraday-version>>
    steps:
      - checkout
      - run: bundle install && bundle exec rspec

workflows:
  version: 2
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              faraday-version: ["0.9.2", "1.0"]
              ruby-version: ["2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7"]
            exclude:
              - faraday-version: "1.0"
                ruby-version: "2.0"
              - faraday-version: "1.0"
                ruby-version: "2.1"
              - faraday-version: "1.0"
                ruby-version: "2.2"
