require_relative './base_service'



# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardless
  module Services
    class CustomerService < BaseService

    
      

            # Creates a new customer object.
        # Example URL: /customers
        # @param options: any query parameters, in the form of a hash
        def create(
          options = {}
        )
        path = nil
        
          path = "/customers"
        

        response = make_request(:post, path, options)
        
          Resources::Customer.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Returns a
    # [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    # list of your customers.
        # Example URL: /customers
        # @param options: any query parameters, in the form of a hash
        def list(
          options = {}
        )
        path = nil
        
          path = "/customers"
        

        response = make_request(:get, path, options)
        
          ListResponse.new(
            raw_response: response,
            unenveloped_body: unenvelope_body(response.body),
            resource_class: Resources::Customer
          )
        
        end

        
        def all(options = {})
          Paginator.new(
            service: self,
            path: "/customers",
            options: options
          ).enumerator
        end
        
        
      

            # Retrieves the details of an existing customer.
        # Example URL: /customers/:identity
        #
        # @param identity:       # Unique identifier, beginning with "CU". }}
        # @param options: any query parameters, in the form of a hash
        def get(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/customers/:identity", { 
            "identity" => identity
          })
        

        response = make_request(:get, path, options)
        
          Resources::Customer.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Updates a customer object. Supports all of the fields supported when
    # creating a customer.
        # Example URL: /customers/:identity
        #
        # @param identity:       # Unique identifier, beginning with "CU". }}
        # @param options: any query parameters, in the form of a hash
        def update(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/customers/:identity", { 
            "identity" => identity
          })
        

        response = make_request(:put, path, options)
        
          Resources::Customer.new(unenvelope_body(response.body))
        
        end

        
        

        def unenvelope_body(body)
          body[envelope_key] || body["data"]
        end

        private

        def envelope_key
          "customers"
        end

        def sub_url(url, param_map)
          param_map.reduce(url) do |new_url, (param, value)|
            new_url.gsub(":#{param}", value)
          end
        end
    end
  end
end

