require_relative './base_service'



# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardless
  module Services
    class EventService < BaseService

    
      

            # Returns a
    # [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    # list of your events.
        # Example URL: /events
        # @param options: any query parameters, in the form of a hash
        def list(
        options = {}, custom_headers = {}
        )
        path = nil
        
          path = "/events"
        

        
        
        
        response = make_request(:get, path, options, custom_headers)
        
          ListResponse.new(
            raw_response: response,
            unenveloped_body: unenvelope_body(response.body),
            resource_class: Resources::Event
          )
        
        end

        
        def all(options = {})
          Paginator.new(
            service: self,
            path: "/events",
            options: options
          ).enumerator
        end
        
        
      

            # Retrieves the details of a single event.
        # Example URL: /events/:identity
        #
        # @param identity:       # Unique identifier, beginning with "EV" }}
        # @param options: any query parameters, in the form of a hash
        def get(
        identity, options = {}, custom_headers = {}
        )
        path = nil
        
          path = sub_url("/events/:identity", { 
            "identity" => identity
          })
        

        
        
        
        response = make_request(:get, path, options, custom_headers)
        
          Resources::Event.new(unenvelope_body(response.body))
        
        end

        
        

        def unenvelope_body(body)
          body[envelope_key] || body["data"]
        end

        private

        def envelope_key
          "events"
        end

        def sub_url(url, param_map)
          param_map.reduce(url) do |new_url, (param, value)|
            new_url.gsub(":#{param}", value)
          end
        end
    end
  end
end

