require_relative './base_service'



# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardless
  module Services
    class PublishableApiKeyService < BaseService
    
      
      # Creates a publishable API key object.
      # Example URL: /publishable_api_keys
      # @param options: parameters as a hash. If the request is a GET, these will be converted to query parameters.
      # Else, they will be the body of the request.
      def create(options = {}, custom_headers = {})
        path = "/publishable_api_keys"
        new_options = {}
        new_options[envelope_key] = options
        options = new_options
        response = make_request(:post, path, options, custom_headers)
        
        Resources::PublishableApiKey.new(unenvelope_body(response.body))
      end
      
      
      # Returns a
# [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
# list of your publishable API keys
      # Example URL: /publishable_api_keys
      # @param options: parameters as a hash. If the request is a GET, these will be converted to query parameters.
      # Else, they will be the body of the request.
      def list(options = {}, custom_headers = {})
        path = "/publishable_api_keys"
        
        response = make_request(:get, path, options, custom_headers)
        ListResponse.new(
          raw_response: response,
          unenveloped_body: unenvelope_body(response.body),
          resource_class: Resources::PublishableApiKey
        )
      end
      
      # Get a lazily enumerated list of all the items returned. This is simmilar to the `list` method but will paginate for you automatically.
      #
      # @param options: parameters as a hash. If the request is a GET, these will be converted to query parameters.
      # Otherwise they will be the body of the request.
      def all(options = {})
        Paginator.new(
          service: self,
          path: "/publishable_api_keys",
          options: options
        ).enumerator
      end
      
      # Returns all details about a single publishable API key
      # Example URL: /publishable_api_keys/:identity
      #
      # @param identity:       # Unique identifier, beginning with "PK" }}
      # @param options: parameters as a hash. If the request is a GET, these will be converted to query parameters.
      # Else, they will be the body of the request.
      def get(identity, options = {}, custom_headers = {})
        path = sub_url("/publishable_api_keys/:identity", { 
          'identity' => identity
        })
        
        
        response = make_request(:get, path, options, custom_headers)
        
        Resources::PublishableApiKey.new(unenvelope_body(response.body))
      end
      
      
      # Updates a publishable API key. Only the `name` fields are supported. Any other
# fields passed will be ignored.
      # Example URL: /publishable_api_keys/:identity
      #
      # @param identity:       # Unique identifier, beginning with "PK" }}
      # @param options: parameters as a hash. If the request is a GET, these will be converted to query parameters.
      # Else, they will be the body of the request.
      def update(identity, options = {}, custom_headers = {})
        path = sub_url("/publishable_api_keys/:identity", { 
          'identity' => identity
        })
        
        new_options = {}
        new_options[envelope_key] = options
        options = new_options
        response = make_request(:put, path, options, custom_headers)
        
        Resources::PublishableApiKey.new(unenvelope_body(response.body))
      end
      
      
      # Disables a publishable API key. Once disabled, the publishable API key will
# not be usable to authenticate any requests.
      # Example URL: /publishable_api_keys/:identity/actions/disable
      #
      # @param identity:       # Unique identifier, beginning with "PK" }}
      # @param options: parameters as a hash. If the request is a GET, these will be converted to query parameters.
      # Else, they will be the body of the request.
      def disable(identity, options = {}, custom_headers = {})
        path = sub_url("/publishable_api_keys/:identity/actions/disable", { 
          'identity' => identity
        })
        
        new_options = {}
        new_options[envelope_key] = options
        options = new_options
        response = make_request(:post, path, options, custom_headers)
        
        Resources::PublishableApiKey.new(unenvelope_body(response.body))
      end
      

      def unenvelope_body(body)
        body[envelope_key] || body['data']
      end

      private

      def envelope_key
        "publishable_api_keys"
      end

      def sub_url(url, param_map)
        param_map.reduce(url) do |new_url, (param, value)|
          new_url.gsub(":#{param}", value)
        end
      end
    end
  end
end

