require_relative './base_service'



# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardless
  module Services
    class RoleService < BaseService

    
      

            # Create a role with set access permissions
        # Example URL: /roles
        # @param options: any query parameters, in the form of a hash
        def create(
          options = {}
        )
        path = nil
        
          path = "/roles"
        

        response = make_request(:post, path, options)
        
          Resources::Role.new(unenvelope_body(response.body))
        
        end

        
        
      

            # List all existing roles
        # Example URL: /roles
        # @param options: any query parameters, in the form of a hash
        def list(
          options = {}
        )
        path = nil
        
          path = "/roles"
        

        response = make_request(:get, path, options)
        
          ListResponse.new(
            raw_response: response,
            unenveloped_body: unenvelope_body(response.body),
            resource_class: Resources::Role
          )
        
        end

        
        def all(options = {})
          Paginator.new(
            service: self,
            path: "/roles",
            options: options
          ).enumerator
        end
        
        
      

            # Retrieve all details for a single role
        # Example URL: /roles/:identity
        #
        # @param identity:       # Unique identifier, beginning with "RO" }}
        # @param options: any query parameters, in the form of a hash
        def get(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/roles/:identity", { 
            "identity" => identity
          })
        

        response = make_request(:get, path, options)
        
          Resources::Role.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Updates a role object. Supports all of the fields supported when creating
    # a role.
        # Example URL: /roles/:identity
        #
        # @param identity:       # Unique identifier, beginning with "RO" }}
        # @param options: any query parameters, in the form of a hash
        def update(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/roles/:identity", { 
            "identity" => identity
          })
        

        response = make_request(:put, path, options)
        
          Resources::Role.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Disables a role
        # Example URL: /roles/:identity/actions/disable
        #
        # @param identity:       # Unique identifier, beginning with "RO" }}
        # @param options: any query parameters, in the form of a hash
        def disable(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/roles/:identity/actions/disable", { 
            "identity" => identity
          })
        

        response = make_request(:post, path, options)
        
          Resources::Role.new(unenvelope_body(response.body))
        
        end

        
        

        def unenvelope_body(body)
          body[envelope_key] || body["data"]
        end

        private

        def envelope_key
          "roles"
        end

        def sub_url(url, param_map)
          param_map.reduce(url) do |new_url, (param, value)|
            new_url.gsub(":#{param}", value)
          end
        end
    end
  end
end

