require_relative './base_service'



# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardless
  module Services
    class SubscriptionService < BaseService

    
      

            # Creates a new subscription object
        # Example URL: /subscriptions
        # @param options: any query parameters, in the form of a hash
        def create(
        options = {}, custom_headers = {}
        )
        path = nil
        
          path = "/subscriptions"
        

        
        
          new_options = {}
          new_options[envelope_key] = options
          options = new_options
        
        
        response = make_request(:post, path, options, custom_headers)
        
          Resources::Subscription.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Returns a
    # [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    # list of your subscriptions.
        # Example URL: /subscriptions
        # @param options: any query parameters, in the form of a hash
        def list(
        options = {}, custom_headers = {}
        )
        path = nil
        
          path = "/subscriptions"
        

        
        
        
        response = make_request(:get, path, options, custom_headers)
        
          ListResponse.new(
            raw_response: response,
            unenveloped_body: unenvelope_body(response.body),
            resource_class: Resources::Subscription
          )
        
        end

        
        def all(options = {})
          Paginator.new(
            service: self,
            path: "/subscriptions",
            options: options
          ).enumerator
        end
        
        
      

            # Retrieves the details of a single subscription.
        # Example URL: /subscriptions/:identity
        #
        # @param identity:       # Unique identifier, beginning with "SB" }}
        # @param options: any query parameters, in the form of a hash
        def get(
        identity, options = {}, custom_headers = {}
        )
        path = nil
        
          path = sub_url("/subscriptions/:identity", { 
            "identity" => identity
          })
        

        
        
        
        response = make_request(:get, path, options, custom_headers)
        
          Resources::Subscription.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Updates a subscription object.
        # Example URL: /subscriptions/:identity
        #
        # @param identity:       # Unique identifier, beginning with "SB" }}
        # @param options: any query parameters, in the form of a hash
        def update(
        identity, options = {}, custom_headers = {}
        )
        path = nil
        
          path = sub_url("/subscriptions/:identity", { 
            "identity" => identity
          })
        

        
        
        
          new_options = {}
          new_options[envelope_key] = options
          options = new_options
        
        response = make_request(:put, path, options, custom_headers)
        
          Resources::Subscription.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Immediately cancels a subscription; no more payments will be created under
    # it. Any metadata supplied to this endpoint will be stored on the payment
    # cancellation event it causes.
    # 
    # This will fail with a
    # cancellation_failed error if the subscription is already cancelled or
    # finished.
        # Example URL: /subscriptions/:identity/actions/cancel
        #
        # @param identity:       # Unique identifier, beginning with "SB" }}
        # @param options: any query parameters, in the form of a hash
        def cancel(
        identity, options = {}, custom_headers = {}
        )
        path = nil
        
          path = sub_url("/subscriptions/:identity/actions/cancel", { 
            "identity" => identity
          })
        

        
        
          new_options = {}
          new_options[envelope_key] = options
          options = new_options
        
        
        response = make_request(:post, path, options, custom_headers)
        
          Resources::Subscription.new(unenvelope_body(response.body))
        
        end

        
        

        def unenvelope_body(body)
          body[envelope_key] || body["data"]
        end

        private

        def envelope_key
          "subscriptions"
        end

        def sub_url(url, param_map)
          param_map.reduce(url) do |new_url, (param, value)|
            new_url.gsub(":#{param}", value)
          end
        end
    end
  end
end

