require_relative './base_service'



# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank

module GoCardless
  module Services
    class UserService < BaseService

    
      

            # <a name="user_exists"></a>Creates a new user object. Email addresses must
    # be unique.
        # Example URL: /users
        # @param options: any query parameters, in the form of a hash
        def create(
          options = {}
        )
        path = nil
        
          path = "/users"
        

        
        
          new_options = {}
          new_options[envelope_key] = options
          options = new_options
        
        
        response = make_request(:post, path, options)
        
          Resources::User.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Returns a
    # [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    # list of your users.
        # Example URL: /users
        # @param options: any query parameters, in the form of a hash
        def list(
          options = {}
        )
        path = nil
        
          path = "/users"
        

        
        
        
        response = make_request(:get, path, options)
        
          ListResponse.new(
            raw_response: response,
            unenveloped_body: unenvelope_body(response.body),
            resource_class: Resources::User
          )
        
        end

        
        def all(options = {})
          Paginator.new(
            service: self,
            path: "/users",
            options: options
          ).enumerator
        end
        
        
      

            # Retrieves the details of an existing user. In addition to the usual
    # permissions based access rules, any user can access their own record.
        # Example URL: /users/:identity
        #
        # @param identity:       # Unique identifier, beginning with "US" }}
        # @param options: any query parameters, in the form of a hash
        def get(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/users/:identity", { 
            "identity" => identity
          })
        

        
        
        
        response = make_request(:get, path, options)
        
          Resources::User.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Updates a user object. Supports all of the fields supported when creating
    # a user.
        # Example URL: /users/:identity
        #
        # @param identity:       # Unique identifier, beginning with "US" }}
        # @param options: any query parameters, in the form of a hash
        def update(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/users/:identity", { 
            "identity" => identity
          })
        

        
        
        
          new_options = {}
          new_options[envelope_key] = options
          options = new_options
        
        response = make_request(:put, path, options)
        
          Resources::User.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Enables a user
        # Example URL: /users/:identity/actions/enable
        #
        # @param identity:       # Unique identifier, beginning with "US" }}
        # @param options: any query parameters, in the form of a hash
        def enable(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/users/:identity/actions/enable", { 
            "identity" => identity
          })
        

        
        
          new_options = {}
          new_options[envelope_key] = options
          options = new_options
        
        
        response = make_request(:post, path, options)
        
          Resources::User.new(unenvelope_body(response.body))
        
        end

        
        
      

            # Disables a user
        # Example URL: /users/:identity/actions/disable
        #
        # @param identity:       # Unique identifier, beginning with "US" }}
        # @param options: any query parameters, in the form of a hash
        def disable(
          identity, options = {}
        )
        path = nil
        
          path = sub_url("/users/:identity/actions/disable", { 
            "identity" => identity
          })
        

        
        
          new_options = {}
          new_options[envelope_key] = options
          options = new_options
        
        
        response = make_request(:post, path, options)
        
          Resources::User.new(unenvelope_body(response.body))
        
        end

        
        

        def unenvelope_body(body)
          body[envelope_key] || body["data"]
        end

        private

        def envelope_key
          "users"
        end

        def sub_url(url, param_map)
          param_map.reduce(url) do |new_url, (param, value)|
            new_url.gsub(":#{param}", value)
          end
        end
    end
  end
end

