# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

require 'json'
require 'zlib'
require 'active_support/inflector'
require 'faraday'
require 'time'
require 'active_support/core_ext/hash/indifferent_access'

require 'uri'

module GoCardless
end

version_file = 'gocardless-pro/version'

if File.file? File.expand_path("#{version_file}.rb", File.dirname(__FILE__))
  require_relative version_file
else
  GoCardless::VERSION = ''
end

require_relative 'gocardless-pro/api_service'
require_relative 'gocardless-pro/list_response'
require_relative 'gocardless-pro/error'
require_relative 'gocardless-pro/error/validation_error'
require_relative 'gocardless-pro/error/gocardless_error'
require_relative 'gocardless-pro/error/invalid_api_usage_error'
require_relative 'gocardless-pro/error/invalid_state_error'
require_relative 'gocardless-pro/paginator'
require_relative 'gocardless-pro/request'
require_relative 'gocardless-pro/response'

require_relative 'gocardless-pro/resources/creditor'
require_relative 'gocardless-pro/services/creditor_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/creditor_bank_account'
require_relative 'gocardless-pro/services/creditor_bank_account_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/customer'
require_relative 'gocardless-pro/services/customer_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/customer_bank_account'
require_relative 'gocardless-pro/services/customer_bank_account_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/event'
require_relative 'gocardless-pro/services/event_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/helper'
require_relative 'gocardless-pro/services/helper_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/mandate'
require_relative 'gocardless-pro/services/mandate_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/payment'
require_relative 'gocardless-pro/services/payment_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/payout'
require_relative 'gocardless-pro/services/payout_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/redirect_flow'
require_relative 'gocardless-pro/services/redirect_flow_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/refund'
require_relative 'gocardless-pro/services/refund_service'
require_relative 'gocardless-pro/client.rb'

require_relative 'gocardless-pro/resources/subscription'
require_relative 'gocardless-pro/services/subscription_service'
require_relative 'gocardless-pro/client.rb'
