# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

require 'json'
require 'zlib'
require 'faraday'
require 'time'

require 'uri'

module GoCardlessPro
end

version_file = 'gocardless_pro/version'

if File.file? File.expand_path("#{version_file}.rb", File.dirname(__FILE__))
  require_relative version_file
else
  GoCardlessPro::VERSION = ''
end

require_relative 'gocardless_pro/api_service'
require_relative 'gocardless_pro/list_response'
require_relative 'gocardless_pro/error'
require_relative 'gocardless_pro/error/validation_error'
require_relative 'gocardless_pro/error/gocardless_error'
require_relative 'gocardless_pro/error/invalid_api_usage_error'
require_relative 'gocardless_pro/error/invalid_state_error'
require_relative 'gocardless_pro/paginator'
require_relative 'gocardless_pro/request'
require_relative 'gocardless_pro/response'
require_relative 'gocardless_pro/api_response'

require_relative 'gocardless_pro/resources/creditor'
require_relative 'gocardless_pro/services/creditors_service'

require_relative 'gocardless_pro/resources/creditor_bank_account'
require_relative 'gocardless_pro/services/creditor_bank_accounts_service'

require_relative 'gocardless_pro/resources/customer'
require_relative 'gocardless_pro/services/customers_service'

require_relative 'gocardless_pro/resources/customer_bank_account'
require_relative 'gocardless_pro/services/customer_bank_accounts_service'

require_relative 'gocardless_pro/resources/event'
require_relative 'gocardless_pro/services/events_service'

require_relative 'gocardless_pro/resources/helper'
require_relative 'gocardless_pro/services/helpers_service'

require_relative 'gocardless_pro/resources/mandate'
require_relative 'gocardless_pro/services/mandates_service'

require_relative 'gocardless_pro/resources/modulus_check'
require_relative 'gocardless_pro/services/modulus_checks_service'

require_relative 'gocardless_pro/resources/payment'
require_relative 'gocardless_pro/services/payments_service'

require_relative 'gocardless_pro/resources/payout'
require_relative 'gocardless_pro/services/payouts_service'

require_relative 'gocardless_pro/resources/redirect_flow'
require_relative 'gocardless_pro/services/redirect_flows_service'

require_relative 'gocardless_pro/resources/refund'
require_relative 'gocardless_pro/services/refunds_service'

require_relative 'gocardless_pro/resources/subscription'
require_relative 'gocardless_pro/services/subscriptions_service'

require_relative 'gocardless_pro/client.rb'
