

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardless
  # A module containing classes for each of the resources in the GC Api
  module Resources
    #
    # Represents an instance of a helper resource returned from the API
    class Helper
      # initialize a resource instance
      # @param object [Hash] an object returned from the API
      def initialize(object)
        @object = object
      end
    end
  end
end
