

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardless
  module Resources
    #
    class Helper
      def initialize(object)
        @object = object
      end

      def envelope_key
        # TODO: could you use $propName here, or use the Envelope property
        'helpers'
      end
    end
  end
end
