

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardless
  module Resources
    # Payouts represent transfers from GoCardless to a
    # [creditor](https://developer.gocardless.com/pro/#api-endpoints-creditors).
    # Each payout contains the funds collected from one or many
    # [payments](https://developer.gocardless.com/pro/#api-endpoints-payments).
    # Payouts are created automatically after a payment has been successfully
    # collected.
    class Payout
      attr_reader :amount

      attr_reader :created_at

      attr_reader :currency

      attr_reader :id

      attr_reader :reference

      attr_reader :status
      def initialize(object)
        @object = object

        @amount = object['amount']
        @created_at = object['created_at']
        @currency = object['currency']
        @id = object['id']
        @links = object['links']
        @reference = object['reference']
        @status = object['status']
      end

      def links
        Struct.new(
          *{

            creditor: '',

            creditor_bank_account: ''

          }.keys
        ).new(*@links.values)
      end

      def envelope_key
        # TODO: could you use $propName here, or use the Envelope property
        'payouts'
      end
    end
  end
end
