

# encoding: utf-8
#
# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#
require 'uri'

module GoCardless
  # A module containing classes for each of the resources in the GC Api
  module Resources
    #
    # Represents an instance of a user resource returned from the API
    class User
      attr_reader :created_at

      attr_reader :email

      attr_reader :enabled

      attr_reader :family_name

      attr_reader :given_name

      attr_reader :id

      # initialize a resource instance
      # @param object [Hash] an object returned from the API
      def initialize(object)
        @object = object

        @created_at = object['created_at']
        @email = object['email']
        @enabled = object['enabled']
        @family_name = object['family_name']
        @given_name = object['given_name']
        @id = object['id']
        @links = object['links']
      end

      # return the links that the resource has
      def links
        Struct.new(
          *{

            role: ''

          }.keys.sort
        ).new(*@links.sort.map(&:last))
      end
    end
  end
end
